---
# Source: github.com/uhlig-it/uhlig.social-deployment
# Secrets (uhlig_social.*) live in the vault.
- name: uhlig.social
  hosts: neon
  become: true
  gather_facts: true
  roles:
    - role: GoToSocial
      vars:
        gts_hostname: "{{ uhlig_social.hostname }}"
        gts_port: "{{ uhlig_social.port | int }}"
        gts_runtime_user: "{{ uhlig_social.runtime_user }}"
        gts_runtime_group: "{{ uhlig_social.runtime_user }}"
        gts_admin_user:
          username: "{{ uhlig_social.admin_user.username }}"
          email: "{{ uhlig_social.admin_user.email }}"
          password: "{{ uhlig_social.admin_user.password }}"
      tags: [gotosocial, fediverse, go, mastodon]
    - role: suhlig.caddy_reverse_proxy
      vars:
        caddy_domain: "{{ uhlig_social.hostname }}"
        caddy_port: "{{ uhlig_social.port | int }}"
      tags: [caddy, https, letsencrypt, proxy]
    - role: uhlig-it.sqlite_backup_b2
      vars:
        sqlite_backup_b2_database_path: "{{ gts_db_path }}"
        sqlite_backup_b2_bucket: suhlig-uhlig-social-backup
        sqlite_backup_b2_keyId: "{{ uhlig_social.backup.keyId }}" # uhlig-social-backup-writer
        sqlite_backup_b2_applicationKey: "{{ uhlig_social.backup.applicationKey }}"
        sqlite_backup_b2_runtime_user: "{{ uhlig_social.runtime_user }}"
        sqlite_backup_b2_runtime_group: "{{ uhlig_social.runtime_user }}"
      become: true
      tags: [sqlite, backup, service, timer]
