werkstatt/door:
  opened: [ cmnd/feinstaub/led/red: { message: "true" } ]
  closed: [ cmnd/feinstaub/led/red: { message: "false" } ]
werkstatt/radio/cmnd:
  "on": [ werkstatt/switch/switchbot/CC:26:79:A1:4A:B5/set: { message: "on" } ]
werkstatt/strom/cmnd:
  on:  [ werkstatt/gosunds/cmnd/power: { message: "on" } ]
  off: [ werkstatt/gosunds/cmnd/power: { message: "off" } ]
werkstatt/licht/hinten/state: # Turn off power whenever the light in the back goes off
  off: [ werkstatt/strom/cmnd: { message: "off" } ]
werkstatt/licht/hinten/cmnd: # Translate the logical command topic into physical servo movement
  on: [ werkstatt/lightservo/cmnd/13: { message: "40°,300ms,110°" } ]
  off: [ werkstatt/lightservo/cmnd/12: { message: "40°,300ms,110°" } ]
werkstatt/lightservo/state: # Translate the physical servo status into logical light state topic
  '{"13":{"angle":{"value":110,"unit":"°"}}}': [ werkstatt/licht/state: { message: "on" } ]
  '{"12":{"angle":{"value":110,"unit":"°"}}}': [ werkstatt/licht/state: { message: "off" } ]