---
galaxy_info:
  role_name: go2rtc
  author: Steffen Uhlig <steffen@familie-uhlig.net>
  description: go2rtc streaming server (republishes local cameras as RTSP for Frigate)
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions: [ 11, 12, 13 ]
dependencies: []
