- name: Directory exists
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    owner: suhlig
    group: suhlig
  with_items:
    - /opt/pi-hole
    - /opt/dnsmasq.d
  become: true
  tags: [ docker, pi-hole, directory ]
- name: Pi-hole is running
  community.docker.docker_container:
    name: pi-hole
    image: pihole/pihole:latest
    pull: true
    state: started
    detach: true
    privileged: true
    restart: true
    restart_policy: always
    env:
      TZ: Europe/Berlin
      WEBPASSWORD: "{{ pi_hole_webpassword }}"
    ports:
      - "53:53/tcp" # DNS
      - "53:53/udp" # DNS
      - "67:67/udp" # Pi-hole as DHCP server
      - "8280:80/tcp" # web interface
    volumes:
      - /opt/pi-hole:/etc/pihole
      - /opt/dnsmasq.d:/etc/dnsmasq.d
    capabilities: [ NET_ADMIN ]
  tags: [ docker, pi-hole, container ]
